#include <stdio.h>
#include "hocdec.h"
#define IMPORT extern __declspec(dllimport)
IMPORT int nrnmpi_myid, nrn_nobanner_;

extern void _BK_reg();
extern void _BK10_reg();
extern void _BK11_reg();
extern void _BK12_reg();
extern void _BK13_reg();
extern void _BK14_reg();
extern void _BK15_reg();
extern void _BK16_reg();
extern void _BK17_reg();
extern void _BK18_reg();
extern void _BK19_reg();
extern void _BK2_reg();
extern void _BK20_reg();
extern void _BK21_reg();
extern void _BK3_reg();
extern void _BK4_reg();
extern void _BK5_reg();
extern void _BK6_reg();
extern void _BK7_reg();
extern void _BK8_reg();
extern void _BK9_reg();
extern void _BK_1_reg();
extern void _BK_2_reg();
extern void _BK_3_reg();
extern void _BK_4_reg();
extern void _BK_5_reg();
extern void _BK_6_reg();
extern void _Cabuffer_reg();
extern void _CadepK_reg();
extern void _Caold_reg();
extern void _Cav12_reg();
extern void _Cav12_1_reg();
extern void _Cav12_2_reg();
extern void _Cav12_3_reg();
extern void _Cav12_4_reg();
extern void _Cav12_5_reg();
extern void _Cav12_6_reg();
extern void _Cav13_reg();
extern void _Cav13_1_reg();
extern void _Cav13_2_reg();
extern void _Cav13_3_reg();
extern void _Cav13_4_reg();
extern void _Cav13_5_reg();
extern void _Cav13_6_reg();
extern void _Cav22_reg();
extern void _Cav2210_reg();
extern void _Cav2211_reg();
extern void _Cav2212_reg();
extern void _Cav2213_reg();
extern void _Cav2214_reg();
extern void _Cav2215_reg();
extern void _Cav2216_reg();
extern void _Cav2217_reg();
extern void _Cav2218_reg();
extern void _Cav2219_reg();
extern void _Cav222_reg();
extern void _Cav2220_reg();
extern void _Cav2221_reg();
extern void _Cav223_reg();
extern void _Cav224_reg();
extern void _Cav225_reg();
extern void _Cav226_reg();
extern void _Cav227_reg();
extern void _Cav228_reg();
extern void _Cav229_reg();
extern void _Cav22_1_reg();
extern void _Cav22_2_reg();
extern void _Cav22_3_reg();
extern void _Cav22_4_reg();
extern void _Cav22_5_reg();
extern void _Cav22_6_reg();
extern void _Cav32_reg();
extern void _Cav32_1_reg();
extern void _Cav32_2_reg();
extern void _Cav32_3_reg();
extern void _Cav32_4_reg();
extern void _Cav32_5_reg();
extern void _Cav32_6_reg();
extern void _HCN_reg();
extern void _Kir21_reg();
extern void _KrueppelAMPA_reg();
extern void _KrueppelNMDA_reg();
extern void _Kv11_reg();
extern void _Kv11_1_reg();
extern void _Kv11_2_reg();
extern void _Kv11_3_reg();
extern void _Kv11_4_reg();
extern void _Kv11_5_reg();
extern void _Kv11_6_reg();
extern void _Kv14_reg();
extern void _Kv14_1_reg();
extern void _Kv14_2_reg();
extern void _Kv14_3_reg();
extern void _Kv14_4_reg();
extern void _Kv14_5_reg();
extern void _Kv14_6_reg();
extern void _Kv21_reg();
extern void _Kv21_1_reg();
extern void _Kv21_2_reg();
extern void _Kv21_3_reg();
extern void _Kv21_4_reg();
extern void _Kv21_5_reg();
extern void _Kv21_6_reg();
extern void _Kv33_reg();
extern void _Kv34_reg();
extern void _Kv34_1_reg();
extern void _Kv34_2_reg();
extern void _Kv34_3_reg();
extern void _Kv34_4_reg();
extern void _Kv34_5_reg();
extern void _Kv34_6_reg();
extern void _Kv42_reg();
extern void _Kv42_1_reg();
extern void _Kv42_2_reg();
extern void _Kv42_3_reg();
extern void _Kv42_4_reg();
extern void _Kv42_5_reg();
extern void _Kv42_6_reg();
extern void _Kv42b_reg();
extern void _Kv723_reg();
extern void _Kv723_1_reg();
extern void _Kv723_2_reg();
extern void _Kv723_3_reg();
extern void _Kv723_4_reg();
extern void _Kv723_5_reg();
extern void _Kv723_6_reg();
extern void _SK2_reg();
extern void _SK2_1_reg();
extern void _SK2_2_reg();
extern void _SK2_3_reg();
extern void _SK2_4_reg();
extern void _SK2_5_reg();
extern void _SK2_6_reg();
extern void _VecStim_reg();
extern void _ichan3_reg();
extern void _ingauss_reg();
extern void _na8st_reg();
extern void _na8st_1_reg();
extern void _na8st_2_reg();
extern void _na8st_3_reg();
extern void _na8st_4_reg();
extern void _na8st_5_reg();
extern void _na8st_6_reg();
extern void _spines_reg();

modl_reg(){
	//nrn_mswindll_stdio(stdin, stdout, stderr);
    if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
	fprintf(stderr, "Additional mechanisms from files\n");

fprintf(stderr," BK.mod");
fprintf(stderr," BK10.mod");
fprintf(stderr," BK11.mod");
fprintf(stderr," BK12.mod");
fprintf(stderr," BK13.mod");
fprintf(stderr," BK14.mod");
fprintf(stderr," BK15.mod");
fprintf(stderr," BK16.mod");
fprintf(stderr," BK17.mod");
fprintf(stderr," BK18.mod");
fprintf(stderr," BK19.mod");
fprintf(stderr," BK2.mod");
fprintf(stderr," BK20.mod");
fprintf(stderr," BK21.mod");
fprintf(stderr," BK3.mod");
fprintf(stderr," BK4.mod");
fprintf(stderr," BK5.mod");
fprintf(stderr," BK6.mod");
fprintf(stderr," BK7.mod");
fprintf(stderr," BK8.mod");
fprintf(stderr," BK9.mod");
fprintf(stderr," BK_1.mod");
fprintf(stderr," BK_2.mod");
fprintf(stderr," BK_3.mod");
fprintf(stderr," BK_4.mod");
fprintf(stderr," BK_5.mod");
fprintf(stderr," BK_6.mod");
fprintf(stderr," Cabuffer.mod");
fprintf(stderr," CadepK.mod");
fprintf(stderr," Caold.mod");
fprintf(stderr," Cav12.mod");
fprintf(stderr," Cav12_1.mod");
fprintf(stderr," Cav12_2.mod");
fprintf(stderr," Cav12_3.mod");
fprintf(stderr," Cav12_4.mod");
fprintf(stderr," Cav12_5.mod");
fprintf(stderr," Cav12_6.mod");
fprintf(stderr," Cav13.mod");
fprintf(stderr," Cav13_1.mod");
fprintf(stderr," Cav13_2.mod");
fprintf(stderr," Cav13_3.mod");
fprintf(stderr," Cav13_4.mod");
fprintf(stderr," Cav13_5.mod");
fprintf(stderr," Cav13_6.mod");
fprintf(stderr," Cav22.mod");
fprintf(stderr," Cav2210.mod");
fprintf(stderr," Cav2211.mod");
fprintf(stderr," Cav2212.mod");
fprintf(stderr," Cav2213.mod");
fprintf(stderr," Cav2214.mod");
fprintf(stderr," Cav2215.mod");
fprintf(stderr," Cav2216.mod");
fprintf(stderr," Cav2217.mod");
fprintf(stderr," Cav2218.mod");
fprintf(stderr," Cav2219.mod");
fprintf(stderr," Cav222.mod");
fprintf(stderr," Cav2220.mod");
fprintf(stderr," Cav2221.mod");
fprintf(stderr," Cav223.mod");
fprintf(stderr," Cav224.mod");
fprintf(stderr," Cav225.mod");
fprintf(stderr," Cav226.mod");
fprintf(stderr," Cav227.mod");
fprintf(stderr," Cav228.mod");
fprintf(stderr," Cav229.mod");
fprintf(stderr," Cav22_1.mod");
fprintf(stderr," Cav22_2.mod");
fprintf(stderr," Cav22_3.mod");
fprintf(stderr," Cav22_4.mod");
fprintf(stderr," Cav22_5.mod");
fprintf(stderr," Cav22_6.mod");
fprintf(stderr," Cav32.mod");
fprintf(stderr," Cav32_1.mod");
fprintf(stderr," Cav32_2.mod");
fprintf(stderr," Cav32_3.mod");
fprintf(stderr," Cav32_4.mod");
fprintf(stderr," Cav32_5.mod");
fprintf(stderr," Cav32_6.mod");
fprintf(stderr," HCN.mod");
fprintf(stderr," Kir21.mod");
fprintf(stderr," KrueppelAMPA.mod");
fprintf(stderr," KrueppelNMDA.mod");
fprintf(stderr," Kv11.mod");
fprintf(stderr," Kv11_1.mod");
fprintf(stderr," Kv11_2.mod");
fprintf(stderr," Kv11_3.mod");
fprintf(stderr," Kv11_4.mod");
fprintf(stderr," Kv11_5.mod");
fprintf(stderr," Kv11_6.mod");
fprintf(stderr," Kv14.mod");
fprintf(stderr," Kv14_1.mod");
fprintf(stderr," Kv14_2.mod");
fprintf(stderr," Kv14_3.mod");
fprintf(stderr," Kv14_4.mod");
fprintf(stderr," Kv14_5.mod");
fprintf(stderr," Kv14_6.mod");
fprintf(stderr," Kv21.mod");
fprintf(stderr," Kv21_1.mod");
fprintf(stderr," Kv21_2.mod");
fprintf(stderr," Kv21_3.mod");
fprintf(stderr," Kv21_4.mod");
fprintf(stderr," Kv21_5.mod");
fprintf(stderr," Kv21_6.mod");
fprintf(stderr," Kv33.mod");
fprintf(stderr," Kv34.mod");
fprintf(stderr," Kv34_1.mod");
fprintf(stderr," Kv34_2.mod");
fprintf(stderr," Kv34_3.mod");
fprintf(stderr," Kv34_4.mod");
fprintf(stderr," Kv34_5.mod");
fprintf(stderr," Kv34_6.mod");
fprintf(stderr," Kv42.mod");
fprintf(stderr," Kv42_1.mod");
fprintf(stderr," Kv42_2.mod");
fprintf(stderr," Kv42_3.mod");
fprintf(stderr," Kv42_4.mod");
fprintf(stderr," Kv42_5.mod");
fprintf(stderr," Kv42_6.mod");
fprintf(stderr," Kv42b.mod");
fprintf(stderr," Kv723.mod");
fprintf(stderr," Kv723_1.mod");
fprintf(stderr," Kv723_2.mod");
fprintf(stderr," Kv723_3.mod");
fprintf(stderr," Kv723_4.mod");
fprintf(stderr," Kv723_5.mod");
fprintf(stderr," Kv723_6.mod");
fprintf(stderr," SK2.mod");
fprintf(stderr," SK2_1.mod");
fprintf(stderr," SK2_2.mod");
fprintf(stderr," SK2_3.mod");
fprintf(stderr," SK2_4.mod");
fprintf(stderr," SK2_5.mod");
fprintf(stderr," SK2_6.mod");
fprintf(stderr," VecStim.mod");
fprintf(stderr," ichan3.mod");
fprintf(stderr," ingauss.mod");
fprintf(stderr," na8st.mod");
fprintf(stderr," na8st_1.mod");
fprintf(stderr," na8st_2.mod");
fprintf(stderr," na8st_3.mod");
fprintf(stderr," na8st_4.mod");
fprintf(stderr," na8st_5.mod");
fprintf(stderr," na8st_6.mod");
fprintf(stderr," spines.mod");
fprintf(stderr, "\n");
    }
_BK_reg();
_BK10_reg();
_BK11_reg();
_BK12_reg();
_BK13_reg();
_BK14_reg();
_BK15_reg();
_BK16_reg();
_BK17_reg();
_BK18_reg();
_BK19_reg();
_BK2_reg();
_BK20_reg();
_BK21_reg();
_BK3_reg();
_BK4_reg();
_BK5_reg();
_BK6_reg();
_BK7_reg();
_BK8_reg();
_BK9_reg();
_BK_1_reg();
_BK_2_reg();
_BK_3_reg();
_BK_4_reg();
_BK_5_reg();
_BK_6_reg();
_Cabuffer_reg();
_CadepK_reg();
_Caold_reg();
_Cav12_reg();
_Cav12_1_reg();
_Cav12_2_reg();
_Cav12_3_reg();
_Cav12_4_reg();
_Cav12_5_reg();
_Cav12_6_reg();
_Cav13_reg();
_Cav13_1_reg();
_Cav13_2_reg();
_Cav13_3_reg();
_Cav13_4_reg();
_Cav13_5_reg();
_Cav13_6_reg();
_Cav22_reg();
_Cav2210_reg();
_Cav2211_reg();
_Cav2212_reg();
_Cav2213_reg();
_Cav2214_reg();
_Cav2215_reg();
_Cav2216_reg();
_Cav2217_reg();
_Cav2218_reg();
_Cav2219_reg();
_Cav222_reg();
_Cav2220_reg();
_Cav2221_reg();
_Cav223_reg();
_Cav224_reg();
_Cav225_reg();
_Cav226_reg();
_Cav227_reg();
_Cav228_reg();
_Cav229_reg();
_Cav22_1_reg();
_Cav22_2_reg();
_Cav22_3_reg();
_Cav22_4_reg();
_Cav22_5_reg();
_Cav22_6_reg();
_Cav32_reg();
_Cav32_1_reg();
_Cav32_2_reg();
_Cav32_3_reg();
_Cav32_4_reg();
_Cav32_5_reg();
_Cav32_6_reg();
_HCN_reg();
_Kir21_reg();
_KrueppelAMPA_reg();
_KrueppelNMDA_reg();
_Kv11_reg();
_Kv11_1_reg();
_Kv11_2_reg();
_Kv11_3_reg();
_Kv11_4_reg();
_Kv11_5_reg();
_Kv11_6_reg();
_Kv14_reg();
_Kv14_1_reg();
_Kv14_2_reg();
_Kv14_3_reg();
_Kv14_4_reg();
_Kv14_5_reg();
_Kv14_6_reg();
_Kv21_reg();
_Kv21_1_reg();
_Kv21_2_reg();
_Kv21_3_reg();
_Kv21_4_reg();
_Kv21_5_reg();
_Kv21_6_reg();
_Kv33_reg();
_Kv34_reg();
_Kv34_1_reg();
_Kv34_2_reg();
_Kv34_3_reg();
_Kv34_4_reg();
_Kv34_5_reg();
_Kv34_6_reg();
_Kv42_reg();
_Kv42_1_reg();
_Kv42_2_reg();
_Kv42_3_reg();
_Kv42_4_reg();
_Kv42_5_reg();
_Kv42_6_reg();
_Kv42b_reg();
_Kv723_reg();
_Kv723_1_reg();
_Kv723_2_reg();
_Kv723_3_reg();
_Kv723_4_reg();
_Kv723_5_reg();
_Kv723_6_reg();
_SK2_reg();
_SK2_1_reg();
_SK2_2_reg();
_SK2_3_reg();
_SK2_4_reg();
_SK2_5_reg();
_SK2_6_reg();
_VecStim_reg();
_ichan3_reg();
_ingauss_reg();
_na8st_reg();
_na8st_1_reg();
_na8st_2_reg();
_na8st_3_reg();
_na8st_4_reg();
_na8st_5_reg();
_na8st_6_reg();
_spines_reg();
}
